package cd.software.flowchat.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF003638)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF1B5A5D)
val onPrimaryContainerLight = Color(0xFFC8FCFF)
val secondaryLight = Color(0xFF4D6263)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFD1E8E9)
val onSecondaryContainerLight = Color(0xFF384C4D)
val tertiaryLight = Color(0xFF3A264C)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF5E4870)
val onTertiaryContainerLight = Color(0xFFFBEDFF)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFF8FAF9)
val onBackgroundLight = Color(0xFF191C1C)
val surfaceLight = Color(0xFFF8FAF9)
val onSurfaceLight = Color(0xFF191C1C)
val surfaceVariantLight = Color(0xFFDBE4E4)
val onSurfaceVariantLight = Color(0xFF404849)
val outlineLight = Color(0xFF707979)
val outlineVariantLight = Color(0xFFBFC8C8)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2E3131)
val inverseOnSurfaceLight = Color(0xFFEFF1F0)
val inversePrimaryLight = Color(0xFF96D1D4)
val surfaceDimLight = Color(0xFFD9DADA)
val surfaceBrightLight = Color(0xFFF8FAF9)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF2F4F3)
val surfaceContainerLight = Color(0xFFEDEEEE)
val surfaceContainerHighLight = Color(0xFFE7E8E8)
val surfaceContainerHighestLight = Color(0xFFE1E3E2)

val primaryLightMediumContrast = Color(0xFF003638)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFF1B5A5D)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF324647)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF63787A)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF3A264C)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFF5E4870)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF8C0009)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFDA342E)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFF8FAF9)
val onBackgroundLightMediumContrast = Color(0xFF191C1C)
val surfaceLightMediumContrast = Color(0xFFF8FAF9)
val onSurfaceLightMediumContrast = Color(0xFF191C1C)
val surfaceVariantLightMediumContrast = Color(0xFFDBE4E4)
val onSurfaceVariantLightMediumContrast = Color(0xFF3C4445)
val outlineLightMediumContrast = Color(0xFF586161)
val outlineVariantLightMediumContrast = Color(0xFF737C7D)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF2E3131)
val inverseOnSurfaceLightMediumContrast = Color(0xFFEFF1F0)
val inversePrimaryLightMediumContrast = Color(0xFF96D1D4)
val surfaceDimLightMediumContrast = Color(0xFFD9DADA)
val surfaceBrightLightMediumContrast = Color(0xFFF8FAF9)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFF2F4F3)
val surfaceContainerLightMediumContrast = Color(0xFFEDEEEE)
val surfaceContainerHighLightMediumContrast = Color(0xFFE7E8E8)
val surfaceContainerHighestLightMediumContrast = Color(0xFFE1E3E2)

val primaryLightHighContrast = Color(0xFF002729)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF014B4E)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF102527)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF324647)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF2D193E)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF4F3A61)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF4E0002)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF8C0009)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFF8FAF9)
val onBackgroundLightHighContrast = Color(0xFF191C1C)
val surfaceLightHighContrast = Color(0xFFF8FAF9)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFDBE4E4)
val onSurfaceVariantLightHighContrast = Color(0xFF1D2526)
val outlineLightHighContrast = Color(0xFF3C4445)
val outlineVariantLightHighContrast = Color(0xFF3C4445)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF2E3131)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFFBBF7FA)
val surfaceDimLightHighContrast = Color(0xFFD9DADA)
val surfaceBrightLightHighContrast = Color(0xFFF8FAF9)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFF2F4F3)
val surfaceContainerLightHighContrast = Color(0xFFEDEEEE)
val surfaceContainerHighLightHighContrast = Color(0xFFE7E8E8)
val surfaceContainerHighestLightHighContrast = Color(0xFFE1E3E2)

val primaryDark = Color(0xFF96D1D4)
val onPrimaryDark = Color(0xFF003739)
val primaryContainerDark = Color(0xFF003F42)
val onPrimaryContainerDark = Color(0xFF99D4D7)
val secondaryDark = Color(0xFFB4CBCC)
val onSecondaryDark = Color(0xFF1F3435)
val secondaryContainerDark = Color(0xFF2F4345)
val onSecondaryContainerDark = Color(0xFFC3D9DA)
val tertiaryDark = Color(0xFFD8BCEC)
val onTertiaryDark = Color(0xFF3C284D)
val tertiaryContainerDark = Color(0xFF453057)
val onTertiaryContainerDark = Color(0xFFDCC0F0)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF111414)
val onBackgroundDark = Color(0xFFE1E3E2)
val surfaceDark = Color(0xFF111414)
val onSurfaceDark = Color(0xFFE1E3E2)
val surfaceVariantDark = Color(0xFF404849)
val onSurfaceVariantDark = Color(0xFFBFC8C8)
val outlineDark = Color(0xFF899293)
val outlineVariantDark = Color(0xFF404849)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE1E3E2)
val inverseOnSurfaceDark = Color(0xFF2E3131)
val inversePrimaryDark = Color(0xFF2B676A)
val surfaceDimDark = Color(0xFF111414)
val surfaceBrightDark = Color(0xFF373A3A)
val surfaceContainerLowestDark = Color(0xFF0C0F0F)
val surfaceContainerLowDark = Color(0xFF191C1C)
val surfaceContainerDark = Color(0xFF1D2020)
val surfaceContainerHighDark = Color(0xFF272A2B)
val surfaceContainerHighestDark = Color(0xFF323535)

val primaryDarkMediumContrast = Color(0xFF9AD5D8)
val onPrimaryDarkMediumContrast = Color(0xFF001A1B)
val primaryContainerDarkMediumContrast = Color(0xFF619A9D)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val secondaryDarkMediumContrast = Color(0xFFB8CFD0)
val onSecondaryDarkMediumContrast = Color(0xFF04191A)
val secondaryContainerDarkMediumContrast = Color(0xFF7F9596)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFFDCC0F0)
val onTertiaryDarkMediumContrast = Color(0xFF200D31)
val tertiaryContainerDarkMediumContrast = Color(0xFFA087B3)
val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val errorDarkMediumContrast = Color(0xFFFFBAB1)
val onErrorDarkMediumContrast = Color(0xFF370001)
val errorContainerDarkMediumContrast = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF111414)
val onBackgroundDarkMediumContrast = Color(0xFFE1E3E2)
val surfaceDarkMediumContrast = Color(0xFF111414)
val onSurfaceDarkMediumContrast = Color(0xFFFAFBFA)
val surfaceVariantDarkMediumContrast = Color(0xFF404849)
val onSurfaceVariantDarkMediumContrast = Color(0xFFC3CCCD)
val outlineDarkMediumContrast = Color(0xFF9BA5A5)
val outlineVariantDarkMediumContrast = Color(0xFF7C8585)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFE1E3E2)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF282B2B)
val inversePrimaryDarkMediumContrast = Color(0xFF0C5053)
val surfaceDimDarkMediumContrast = Color(0xFF111414)
val surfaceBrightDarkMediumContrast = Color(0xFF373A3A)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF0C0F0F)
val surfaceContainerLowDarkMediumContrast = Color(0xFF191C1C)
val surfaceContainerDarkMediumContrast = Color(0xFF1D2020)
val surfaceContainerHighDarkMediumContrast = Color(0xFF272A2B)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF323535)

val primaryDarkHighContrast = Color(0xFFEBFEFF)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFF9AD5D8)
val onPrimaryContainerDarkHighContrast = Color(0xFF000000)
val secondaryDarkHighContrast = Color(0xFFEBFEFF)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFB8CFD0)
val onSecondaryContainerDarkHighContrast = Color(0xFF000000)
val tertiaryDarkHighContrast = Color(0xFFFFF9FB)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFFDCC0F0)
val onTertiaryContainerDarkHighContrast = Color(0xFF000000)
val errorDarkHighContrast = Color(0xFFFFF9F9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFBAB1)
val onErrorContainerDarkHighContrast = Color(0xFF000000)
val backgroundDarkHighContrast = Color(0xFF111414)
val onBackgroundDarkHighContrast = Color(0xFFE1E3E2)
val surfaceDarkHighContrast = Color(0xFF111414)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF404849)
val onSurfaceVariantDarkHighContrast = Color(0xFFF3FCFC)
val outlineDarkHighContrast = Color(0xFFC3CCCD)
val outlineVariantDarkHighContrast = Color(0xFFC3CCCD)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFE1E3E2)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF003032)
val surfaceDimDarkHighContrast = Color(0xFF111414)
val surfaceBrightDarkHighContrast = Color(0xFF373A3A)
val surfaceContainerLowestDarkHighContrast = Color(0xFF0C0F0F)
val surfaceContainerLowDarkHighContrast = Color(0xFF191C1C)
val surfaceContainerDarkHighContrast = Color(0xFF1D2020)
val surfaceContainerHighDarkHighContrast = Color(0xFF272A2B)
val surfaceContainerHighestDarkHighContrast = Color(0xFF323535)














